name: 🔗 Check URLs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: --verbose --no-progress --timeout=30 './**/*.md' 